# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InterfaceUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MyWindow(object):
    def setupUi(self, MyWindow):
        MyWindow.setObjectName("MyWindow")
        MyWindow.resize(961, 705)
        self.centralwidget = QtWidgets.QWidget(MyWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 40, 860, 590))
        self.frame.setMinimumSize(QtCore.QSize(860, 590))
        self.frame.setStyleSheet("#frame{\n"
"    background-color: rgb(255, 255, 255);\n"
"  border-top-left-radius:10px;\n"
"  border-top-right-radius:10px;\n"
"  border-bottom-left-radius:10px;\n"
"  border-bottom-right-radius:10px;\n"
"    \n"
"\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("#frame_2{\n"
"  background-color: rgb(255, 255, 255);\n"
"  border-top-left-radius:20px;\n"
"  border-top-right-radius:20px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.horizontalLayout.addWidget(self.frame_4, 0, QtCore.Qt.AlignLeft)
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_logout = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_logout.setObjectName("pushButton_logout")
        self.horizontalLayout_3.addWidget(self.pushButton_logout)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.horizontalLayout.addWidget(self.frame_5, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setStyleSheet("#frame_6{\n"
"    background-color: rgb(85, 85, 127);\n"
"    border-bottom-left-radius:20px;\n"
"    border-top-right-radius:20px;\n"
"}\n"
"\n"
"QPushButton{\n"
"border:none;\n"
"color:rgb(255, 255, 255);\n"
"font: 12pt \"幼圆\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(218, 218, 218);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"padding-top:5px;\n"
"\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_home = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_home.setStyleSheet("")
        self.pushButton_home.setObjectName("pushButton_home")
        self.verticalLayout_2.addWidget(self.pushButton_home)
        self.pushButton_web = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_web.setStyleSheet("")
        self.pushButton_web.setObjectName("pushButton_web")
        self.verticalLayout_2.addWidget(self.pushButton_web)
        self.pushButton_my = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_my.setStyleSheet("")
        self.pushButton_my.setObjectName("pushButton_my")
        self.verticalLayout_2.addWidget(self.pushButton_my)
        self.horizontalLayout_4.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setStyleSheet("#frame_7{\n"
"    background-color: rgb(255, 255, 255);\n"
"border-bottom-right-radius:20px;\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_7)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_home = QtWidgets.QWidget()
        self.page_home.setObjectName("page_home")
        self.label = QtWidgets.QLabel(self.page_home)
        self.label.setGeometry(QtCore.QRect(170, 220, 361, 121))
        self.label.setStyleSheet("font: 20pt \"华文行楷\";")
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.page_home)
        self.page_web = QtWidgets.QWidget()
        self.page_web.setObjectName("page_web")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_web)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_8 = QtWidgets.QFrame(self.page_web)
        self.frame_8.setMinimumSize(QtCore.QSize(370, 390))
        self.frame_8.setMaximumSize(QtCore.QSize(370, 390))
        self.frame_8.setStyleSheet("QPushButton{\n"
"border:2px solid gray;\n"
"border-radius:7px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(230, 230, 230);\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_bilibili = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_bilibili.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_bilibili.setObjectName("pushButton_bilibili")
        self.verticalLayout_5.addWidget(self.pushButton_bilibili)
        self.pushButton_csdn = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_csdn.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_csdn.setObjectName("pushButton_csdn")
        self.verticalLayout_5.addWidget(self.pushButton_csdn)
        self.pushButton_apple = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_apple.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_apple.setObjectName("pushButton_apple")
        self.verticalLayout_5.addWidget(self.pushButton_apple)
        self.pushButton_vedio = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_vedio.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_vedio.setObjectName("pushButton_vedio")
        self.verticalLayout_5.addWidget(self.pushButton_vedio)
        self.verticalLayout_4.addWidget(self.frame_8, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget.addWidget(self.page_web)
        self.page_my = QtWidgets.QWidget()
        self.page_my.setObjectName("page_my")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_my)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_9 = QtWidgets.QFrame(self.page_my)
        self.frame_9.setMinimumSize(QtCore.QSize(370, 390))
        self.frame_9.setMaximumSize(QtCore.QSize(370, 390))
        self.frame_9.setStyleSheet("QPushButton{\n"
"    background-color: rgb(244, 255, 202);\n"
"border:2px solid gray;\n"
"border-radius:7px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 255, 73);\n"
"}")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lineEdit_m_pass = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_m_pass.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_m_pass.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_m_pass.setObjectName("lineEdit_m_pass")
        self.verticalLayout_6.addWidget(self.lineEdit_m_pass)
        self.lineEdit_m_pass_sure = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_m_pass_sure.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_m_pass_sure.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_m_pass_sure.setObjectName("lineEdit_m_pass_sure")
        self.verticalLayout_6.addWidget(self.lineEdit_m_pass_sure)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_4.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_6.addWidget(self.pushButton_4)
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.frame_9)
        self.stackedWidget_2.setMinimumSize(QtCore.QSize(0, 40))
        self.stackedWidget_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget_2.addWidget(self.page)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_2 = QtWidgets.QLabel(self.page_3)
        self.label_2.setGeometry(QtCore.QRect(30, 0, 297, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.stackedWidget_2.addWidget(self.page_3)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_3 = QtWidgets.QLabel(self.page_2)
        self.label_3.setGeometry(QtCore.QRect(30, 0, 297, 51))
        self.label_3.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.stackedWidget_2.addWidget(self.page_2)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label_4 = QtWidgets.QLabel(self.page_4)
        self.label_4.setGeometry(QtCore.QRect(20, 0, 297, 51))
        self.label_4.setStyleSheet("color:rgb(0, 170, 0)")
        self.label_4.setObjectName("label_4")
        self.stackedWidget_2.addWidget(self.page_4)
        self.verticalLayout_6.addWidget(self.stackedWidget_2)
        self.verticalLayout_7.addWidget(self.frame_9, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget.addWidget(self.page_my)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.horizontalLayout_4.addWidget(self.frame_7)
        self.verticalLayout.addWidget(self.frame_3)
        MyWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MyWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(0)
        self.pushButton_2.clicked.connect(MyWindow.close) # type: ignore
        self.pushButton_3.clicked.connect(MyWindow.showMinimized) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MyWindow)

    def retranslateUi(self, MyWindow):
        _translate = QtCore.QCoreApplication.translate
        MyWindow.setWindowTitle(_translate("MyWindow", "MainWindow"))
        self.pushButton.setText(_translate("MyWindow", "Barry"))
        self.pushButton_logout.setText(_translate("MyWindow", "退出"))
        self.pushButton_3.setText(_translate("MyWindow", "缩小"))
        self.pushButton_2.setText(_translate("MyWindow", "关闭"))
        self.pushButton_home.setText(_translate("MyWindow", "首页"))
        self.pushButton_web.setText(_translate("MyWindow", "网址推荐"))
        self.pushButton_my.setText(_translate("MyWindow", "我的"))
        self.label.setText(_translate("MyWindow", "欢迎登陆我的首页"))
        self.pushButton_bilibili.setText(_translate("MyWindow", "BiliBili"))
        self.pushButton_csdn.setText(_translate("MyWindow", "CSDN"))
        self.pushButton_apple.setText(_translate("MyWindow", "APPLE"))
        self.pushButton_vedio.setText(_translate("MyWindow", "VEDIO"))
        self.lineEdit_m_pass.setPlaceholderText(_translate("MyWindow", "密码："))
        self.lineEdit_m_pass_sure.setPlaceholderText(_translate("MyWindow", "确认密码"))
        self.pushButton_4.setText(_translate("MyWindow", "确定"))
        self.label_2.setText(_translate("MyWindow", "         账号和密码不能为空"))
        self.label_3.setText(_translate("MyWindow", "            两次密码不一致"))
        self.label_4.setText(_translate("MyWindow", "             密码修改成功"))
